
spring:
#  main:
#    allow-bean-definition-overriding: true

  application:
    name: notification-service

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    dead_letter_topic: notification-retry


    topic:
      name: notification

    bootstrap-servers: localhost:9092

  datasource:
#    url: jdbc:postgresql://8.219.131.180:8765/fintrack
#    username: root
#    password: P@SSWORD666
    url: jdbc:postgresql://localhost:33007/mini_project_db
    username: my_user
    password: my_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#hibernate:
#  jdbc:
logging:
  level:
    com.levi.testhibernate: debug
#    batch_size: 1

kafka:
  group-id: notification-consumer
  auto-offset: earliest

server:
  port: 8087

